### ISSUE TITLE
Pypi 1.0.0rc1 install fail

### ISSUE THREAD

**Issue by cquest** [addok/addok#279] opened 2017-03-04 08:37 UTC
When launching addok shell:

 ```
Traceback (most recent call last):
  File "/home/addok/.virtualenvs/addok2/bin/addok", line 11, in <module>
    sys.exit(main())
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/bin/__init__.py", line 21, in main
    config.load()
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/config/__init__.py", line 32, in load
    self.load_core_plugins()
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/config/__init__.py", line 55, in load_core_plugins
    plugin = importlib.import_module(path)
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/batch/__init__.py", line 4, in <module>
    from .utils import batch
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/batch/utils.py", line 4, in <module>
    from addok.index_utils import deindex_document, index_document
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/index_utils.py", line 5, in <module>
    from .textutils.default import compute_edge_ngrams
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/textutils/default/__init__.py", line 37, in <module>
    load_synonyms()
  File "/home/addok/.virtualenvs/addok2/lib/python3.4/site-packages/addok/textutils/default/__init__.py", line 25, in load_synonyms
    with config.RESOURCES_ROOT.joinpath(config.SYNONYMS_PATH).open() as f:
AttributeError: 'module' object has no attribute 'RESOURCES_ROOT'
```

**Comment by davidbgk** [comment] 2017-03-04 14:28
Duplicate of #265

**Closed by davidbgk** 2017-03-04 14:28 UTC
