### ISSUE TITLE
CSV - WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by dzaouch** [addok/addok#176] opened 2016-06-27 07:03 UTC
Hi,

On v0.5, I got this error by using the csv, so i don't know which line makes it crashes and why.

Can you tell me why it's crashing ?

[2016-06-24 12:49:42 +0200] [14784] [ERROR] Error handling request /csv
Traceback (most recent call last):
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/gunicorn/workers/gthread.py", line 274, in handle
keepalive = self.handle_request(req, conn)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 63, in app
response = View.serve(endpoint, request, kwargs)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 103, in serve
response = view.post(kwargs)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 338, in post
self.process_rows()
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 313, in process_rows
self.process_row(row)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/addok/server.py", line 384, in process_row
results = search(q, autocomplete=False, limit=1, *filters)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 778, in search
return helper(query, lat=lat, lon=lon, *filters)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 401, in call
if step():
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 505, in step_fuzzy
self.fuzzy(self.meaningful, include_common=False)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/addok/core.py", line 599, in fuzzy
fuzzy_words = DB.sinter(interkeys)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 1516, in sinter
return self.execute_command('SINTER', args)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 573, in execute_command
return self.parse_response(connection, command_name, *options)
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 585, in parse_response
response = connection.read_response()
File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/redis/connection.py", line 582, in read_response
raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value

**Comment by yohanboniface** [comment] 2016-06-27 07:17
Sounds like a duplicate of #170.

**Closed by yohanboniface** 2016-06-27 07:17 UTC

**Comment by dzaouch** [comment] 2016-06-27 07:20
I wasn't sure, because it's when i call the csv url and also the error seems to occurs when this is called :

File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 1516, in sinter
return self.execute_command('**SINTER**', args)

or this :

File "/home/devel/.virtualenvs/addok/lib/python3.4/site-packages/redis/client.py", line 1516, in sinter
return self.execute_command('**SADD**', args)
